# https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/rbac.md#prometheus-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: monitoring-prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: monitoring-prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: monitoring-prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
  name: prometheus
  namespace: monitoring
---
kind: Alertmanager
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    k8s-app: monitoring-alertmanager
    release: monitoring
  name: monitoring-alertmanager
  namespace: monitoring
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector: {}
  image: "quay.io/prometheus/alertmanager:v0.21.0"
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: web
  replicas: 1
  retention: 120h
  routePrefix: /
  podMetadata:
    labels:
      k8s-app: monitoring-alertmanager
      release: monitoring
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  version: v0.21.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: monitoring-alertmanager
  name: monitoring-alertmanager
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: monitoring-alertmanager
    k8s-app: monitoring-alertmanager
---
kind: Prometheus
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    k8s-app: monitoring-prometheus
    release: monitoring
  name: monitoring-prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: monitoring-alertmanager
        namespace: prometheus
        pathPrefix: /
        port: web
  enableAdminAPI: false
  image: "quay.io/prometheus/prometheus:v2.26.1"
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: web
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  retention: 10d
  routePrefix: /
  podMetadata:
    labels:
      k8s-app: monitoring-prometheus
      release: monitoring
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  serviceAccountName: prometheus
  shards: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  version: v2.26.1
---
kind: Service
apiVersion: v1
metadata:
  name: monitoring-prometheus
  namespace: monitoring
  labels:
    k8s-app: monitoring-prometheus
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    k8s-app: monitoring-prometheus
    release: monitoring
  type: ClusterIP
  sessionAffinity: None
