---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-gatus-ep
  namespace: networking
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: traefik
        group: external
        url: https://ingress.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions: ["[CONNECTED] == true"]
        ui:
          hide-url: true
          hide-hostname: true
