kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: reviewapps
  namespace: argocd
spec:
  destination:
    namespace: dynamic-environments-reviewapps
    server: 'https://kubernetes.default.svc'
  project: reviewapps-project
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: k8s/manifests/overlays/development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
