apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: reviewapps-project
  namespace: argocd
  labels:
    app: reviewapps
spec:
  # Project description
  description: Our ArgoCD Project to deploy our app locally
  # Allow manifests to deploy only from argoproj git repositories
  sourceRepos:
    - "https://github.com/argoproj/*"
  destinations:
    - namespace: "*"
      server: "*"
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
