---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-common-apps-error-pages
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-traefik
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/cluster-common/apps/networking/error-pages/app  # FIXME
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
