---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-goldilocks
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-vpa
  path: ./k8s/cluster-common/apps/monitoring/goldilocks/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: goldilocks
      namespace: monitoring
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
