apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/reviewapp.name: app
  app.kubernetes.io/reviewapp.version: v0.0.1
fieldSpecs:
  - path: metadata/labels
    create: true
