# https://external-secrets.io/latest/provider/fake/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: fake
    namespace: kube-system
spec:
    provider:
        fake:
            data:
                - key: ENC[AES256_GCM,data:nt8vqveCZnajVGbrBVl1/qQR9wmugpugQweJ6Q==,iv:q+FWYHW9US7l0smONqibEt6KydAPEKZWpJKzT3yzQMc=,tag:H+K2T5eFwl59jymBxL0QUA==,type:str]
                  value: ENC[AES256_GCM,data:lISQ34JeUgAHbeIisA==,iv:Z+JsABC3g4SEHaCrqt3R633jHFvZ3soJ7hUculMqlIc=,tag:59XbMJQduNaqZOWdtqpVnQ==,type:str]
                  version: ENC[AES256_GCM,data:Ckg=,iv:mI+7QG8a2+jmE6Xenctt/0gl4yvl8wZ7RPFngvncueo=,tag:dA8m3KwLllB7WEEpU+b0ng==,type:str]
                - key: ENC[AES256_GCM,data:7dCqnVHpzE4vMtMD9tCuWdb1sBbVzQy7rspGjQ==,iv:T/r1i+l5GzAQsHDzPSYw+kiv7Vj6Ry0UBZ6+Jibm8mo=,tag:986XMxl+8x0vZBxyQxFWtw==,type:str]
                  value: ENC[AES256_GCM,data:uDg4KsmLyNjstxeqWyCcpyMLJ80BTgD+vQ==,iv:tbz8UiEWMAqZPoHxpieSFeQ4P3fqQ44g+6YLUsoNYmQ=,tag:BMPqtZjrP/anUtSs8s4vGA==,type:str]
                  version: ENC[AES256_GCM,data:bCk=,iv:6m0jRJnfX1Uopik7pETofuK0KJsBm6X78LJdFfUpzeo=,tag:1OgqyawXSyY3rwC5yLjDaw==,type:str]
                - key: ENC[AES256_GCM,data:9mwGVde5hdMLVaaZdQdRo7Oct0hRxNAgVp/SDz4CKkr15DvOVXnLsyAdBRg=,iv:ooSc+LbBNUI77k8ogi6p2iUHaU/tnqNUfH0BBEqIjb8=,tag:xlLvFpvr9Dc9wWb0YATs6A==,type:str]
                  value: ENC[AES256_GCM,data:5YlP+SEKTT6znchbVf+Z9qnHwQHAWOr1Dz0=,iv:N/NYirpyRfXErM2MeQg7wdTYo4pDQ8ENTj+eOcq2PVA=,tag:6QHwXa2D54lF4MVjeXGauQ==,type:str]
                  version: ENC[AES256_GCM,data:Vws=,iv:HZOpy9koXidfl+ocE7AaVzQOiUSKvoHbOLmb3PzswZk=,tag:kfan18L1swlSzzlJuBaeBA==,type:str]
                - key: ENC[AES256_GCM,data:YjZ8Oo2aqUxcJVdSbiWbYh87baHeLLXZhVZDpk8low==,iv:ScNTfUYJFMcd7PO/5ScEHmpczBjpg17o38+cJL3X5C0=,tag:jGfWQELHZKcBOTvMl/IrtQ==,type:str]
                  value: ENC[AES256_GCM,data:D2fgq0dUqoxNmTD5guwQeXbc19VIQ0InNNM4/iQO6WIyAgnHAvZNV14lYo3ymB9EVTpr,iv:g8faos3M7i6edsWimgcy9Ic3qLhHY3F984OmzGxmnLw=,tag:EOEGzEWbcV8H9PsDIvWh3w==,type:str]
                  version: ENC[AES256_GCM,data:d7o=,iv:QRf92uSJyWjMdZkxvZktd0x/X+vimWxx7hUDMZM86yo=,tag:GwLFLoFtkgvrBOpxPyrk+w==,type:str]
                - key: ENC[AES256_GCM,data:bbDGDOWdsDwd5g==,iv:cBG5xKU76Y2bAdZ0PfxC0z+5RBftjzE8O6ffN6O6fiw=,tag:9exq+c+5Dczh9dw2VTUVoQ==,type:str]
                  valueMap:
                    foo: ENC[AES256_GCM,data:LUd0RczymQ==,iv:iQaq1XbCcom8bQr9vH9T1EGxluC8Vh/W5K8mtnbI0z4=,tag:yy1HelfJZMePL2U19OuoBQ==,type:str]
                    other: ENC[AES256_GCM,data:7gbvQSM=,iv:XS6DUch0GKj49MX4gpDuBsFRZVcqKsmedcLDEWGhLRs=,tag:8LXA0l+FUYG8LsZV6U/kTw==,type:str]
                - key: ENC[AES256_GCM,data:aYjtw4SvBoZa6OEmFMdwjD7srbg=,iv:+v/AqA8gtXW3QCydAYPNw51eiOPl7fxnxHXKWiRVEDs=,tag:K7mP84LoQ25Da+9mpZ2aSg==,type:str]
                  valueMap:
                    #ENC[AES256_GCM,data:GnfB28iCnB1rmkdkRuoplbfbarqowGRm+eDhx1YER/hEZL0XpKTTJq9Y7Y2+,iv:dMPIpbif7xo0VgqCCqut28epiZVxGenSQFdCcTYmOQ8=,tag:4BxmuK9KjWwb7BpRXtJTTw==,type:comment]
                    users: ENC[AES256_GCM,data:57UUJ6Daeq/Qd1oWL3X7BsZJKAAd9ap/JDeh2avFp+8q2upr8kB8Cai0A1WBfZK/DFYujolCUaGGds4c,iv:DTS4FDAGKc9yrkJnNV9uFDWKhhNBbeDephG0p/aJ9Ho=,tag:90ghfp8bqQH5pqBsM/Bs3w==,type:str]
                    #ENC[AES256_GCM,data:ye+4tAG3HtyTk8nsHagX7BM=,iv:CZHqKexRQdT8IwAIdtMXAx5Bq59uXUsCU+/0FtQ8Nx8=,tag:onPQEi/LMl4qQOLG2Vub+w==,type:comment]
                    apps: ENC[AES256_GCM,data:d/HwTQkyvbY+3Uc6SQlSdrcPRIfDgD4UMCJ0vqusR0NR1PkWy7U=,iv:4mFOPF/AI4bFZSiQukX/NjznVJ1dBuKmtzwnAVhOqBY=,tag:rOTpFBq407i/uV09MyGw7g==,type:str]
                    #ENC[AES256_GCM,data:3764XliUsBKNt+JKZ4q5JaZBneFIJZdwUb7zAZUw,iv:7TbVmDu3MdaWgmgxi8KsMbMUbAbZy5Edc1g7RLy402Y=,tag:QK7n5gyikFmKpE4KevP8LQ==,type:comment]
                    services: ENC[AES256_GCM,data:/bYJB8DtLo2DTF0QucXKvqRWs5IxbVIB8auZJZ696uPWOwUT50KJ7LYb,iv:6NbY42O/q8qRA25FzbRZORMHIuswpfpNcK8KY1TO3tU=,tag:hw8zzdgMUMomIf1X8gVKVA==,type:str]
                  version: ENC[AES256_GCM,data:bWE=,iv:0Do5zpprnpGgiRFG9s8xdokOdOHeJVvGeDwX7pqYqzA=,tag:5wr/dLvvStGbF62dNilYiA==,type:str]
                - key: ENC[AES256_GCM,data:zeP8t2Gf4Mjd5jQ7q2fo/pXyX/UjSXEYRb1m4Aw=,iv:sjMuoW8CwiRSHmTtcAw7H7yPAG58HkbmJizN76bwsjM=,tag:xwXjcRjYypm7gQUvdPcn+w==,type:str]
                  version: ENC[AES256_GCM,data:1Gc=,iv:EEdtUDY0XwfR6p0t1kVfuDNmsqhplltYl9hLDMsFqwc=,tag:zmxtYWK6HnBgQKnjFMvHjQ==,type:str]
                  valueMap:
                    username: ENC[AES256_GCM,data:EB5uFq0cZXc8o0xQ0w==,iv:JtfGHO9VsrFVGdz/pKRXksAKbmLzqXbzN67Z37YllBk=,tag:gI86xIquXJy47VWLjT+01A==,type:str]
                    password: ENC[AES256_GCM,data:RiJAcqcEohE9e87QQiYi/9M+ORF9PXoje4vByVHH1w7V4GcjhdXnkU3RfJJ/0icsnBC2URSHBjkL97xd4mOC,iv:ADaBGv0c3gjMToZky8l2H0qKmk99k8kl309/ipLFT9M=,tag:vCIeGRHBCtNBrp6ILBJqDQ==,type:str]
                    init_postgres_super_pass: ENC[AES256_GCM,data:cxYCcnzDjyyQh8a5irX8DraPI3nvGJHAci4XQwHj2JU8IWVdOurk7Uw342Mn/qOrHeszGjdtpX754Q==,iv:K/8ErdL7qyZ5DkDjwhtGr1ZJVcINcFeaHjWI4x3Rz0o=,tag:++/lFzLvfI06tod3PnT9hg==,type:str]
                - key: ENC[AES256_GCM,data:ZIsz0LuBJJw8j2ZAFNyS+/JL5qfRW+looyDkczc=,iv:7WZralFNM4hfElMs7Pr18qxiUBLxbiTu+c8p12Fv2Do=,tag:ntAPgfrWgyHB2NOCB/9JkA==,type:str]
                  version: ENC[AES256_GCM,data:D5w=,iv:zmhe4VPdoO9UqrKudYTQjY+54NhShH1uYfGwGYT5bmA=,tag:ByIYlVYw2eaLIjx3uNLlMQ==,type:str]
                  valueMap:
                    ssh_key: ENC[AES256_GCM,data:kZd7,iv:rXTrnz/ctd4Ft6geMJRLUg1MOmLUiTu+4gNGSuRbNYA=,tag:QbhiQJk7ZlGqvHZcuuPo4Q==,type:str]
                - key: ENC[AES256_GCM,data:IoaQXaz7VRhIUeCNHjIQ/MFsbNuAP/jzIf/w6uO0UQ==,iv:iPsviZ3R+fhZvY0xwgWt8hu8p6B98lHvyy70svMR7So=,tag:LGGHuKtdsdR9f48QbbXLrg==,type:str]
                  value: ENC[AES256_GCM,data:u4Sb0YM=,iv:ndkc928T9R7bET+kTCevs+eV6GQtl8oUgiR7sMiPBTs=,tag:ffkCgn3efowbDg9HNMwyZw==,type:str]
                  version: ENC[AES256_GCM,data:EII=,iv:/IX2f5Mbk3RcuPUCMaqOoC47eQ7O7Gclao+dhSVYFLQ=,tag:KlKmTIy+gpVLI8EmBsNCnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2blduRzlOZE1xaEtkVlF5
            QmZCMkNJYVhNTS9qc0ZVRnY5RGdlMlhCS2xzCjE2NTgrZTFrRk1YbVl1VHB5U0JH
            LzZsTVU3bGZxelhvOERXUUlVMDlvUTAKLS0tIFdNRkdOZjFFNTJ3NmJYek1seE1Z
            c3g2dWNDUGpsRGFIZHdZSlE0aUtxV3cKdBj+rIU+8DB8GkDnnkmIJEchYEcRJBnq
            +mqd7+93+D5HBqR9FdsD5Ck5aLHQB0Ls73Khw69wtNJrKbvJvyki0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T14:37:23Z"
    mac: ENC[AES256_GCM,data:5xr3T8T3pdWnyZFiieZ1mLAtAB25saBdUC+fSgOwGeFnoN7F0tjnomhVy4M4vWny9GjkmDbJaXOmvTA61p1a+5bs86zeEMUOUD0jtqIQYopsswbHy8KBPNMchzgTsfoLQuvluNz9BbUyPDY8Rplt0v5GrIthISvbhD17bXAucBo=,iv:bh3bGZoYIduoQPmZuvYd2X5MOSQ6VE0+ZrWspVtNVyo=,tag:FoEK2Oe33fRdKIBpoW8TDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules|value|key)$
    version: 3.7.3
