---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kube-tools
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 2.7.5
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m
  values:
    crds:
      install: true

    replicaCount: 3

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1

    grafana:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m
    backgroundController:
      serviceMonitor:
        enabled: true
    cleanupController:
      serviceMonitor:
        enabled: true
    reportsController:
      serviceMonitor:
        enabled: true

    resources:
      requests:
        cpu: 247m
        memory: 443M
      limits:
        memory: 1336M

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: kyverno
