---
# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/main/pkg/config/v1alpha5/schema.json
# https://k3d.io/usage/configfile/
kind: Simple
apiVersion: k3d.io/v1alpha5
metadata:
  name: ${CLUSTER_NAME}
servers: 1
agents: 3
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
image: rancher/k3s:v1.27.4-k3s1
subnet: "172.28.0.0/16"
volumes:
- volume: ${SHARED_PATH}:/mnt/shared
  nodeFilters:
  - all
- volume: ${SHARED_PATH}/default-local-pv:/opt/local-path-provisioner
  nodeFilters:
  - all
ports:
- port: 0.0.0.0:1080:30080 # Traefik http endpoint
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:1443:30443 # Traefik https endpoint
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:32600:32600 # Traefik TCP endpoint
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:32700:32700 # Traefik UDP endpoint
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:7844:32766 # Cloudflared quick
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:30053:30053 # DNS k8s-gateway
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: 1m30s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  k3s:
    extraArgs:
    - arg: --disable=traefik,servicelb,local-storage,metrics-server
      nodeFilters:
      - server:*
    - arg: --tls-san=${CURRENT_IP}
      nodeFilters:
      - server:*
    - arg: --tls-san=${CURRENT_EXTERNAL_IP}
      nodeFilters:
      - server:*
    - arg: --tls-san=dxas90.duckdns.org
      nodeFilters:
      - server:*
    - arg: --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
      nodeFilters:
      - agent:*
    - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
      nodeFilters:
      - agent:*
    nodeLabels:
      - label: nerdctl/bypass4netns=true
        nodeFilters:
        - all
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
    - label: my.k3s.cluster=true
      nodeFilters:
      - all
    - label: nerdctl/bypass4netns=true
      nodeFilters:
      - all
env:
- envVar: SHARED_PATH=${SHARED_PATH}
  nodeFilters:
  - all
