# https://k3d.io/usage/configfile/
---
apiVersion: k3d.io/v1alpha2
kind: Simple
name: ${CLUSTER_NAME}
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.20.8-k3s1
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
ports:
  - port: 0.0.0.0:80:30080
    nodeFilters:
      - agent[0]
  - port: 0.0.0.0:443:30443
    nodeFilters:
      - agent[0]
volumes:
  - volume: ${SHARED_PATH}:/mnt/shared
    nodeFilters:
      - all
env:
  - envVar: SHARED_PATH=${SHARED_PATH}
    nodeFilters:
      - all
labels:
  - label: "k3s.cluster=true"
    nodeFilters:
      - all
options:
  k3d:
    wait: true
    timeout: "90s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraServerArgs:
      - --disable=traefik,servicelb,local-storage,metrics-server
      - --tls-san=${CURRENT_IP}
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
