---
# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/main/pkg/config/v1alpha5/schema.json
# https://k3d.io/usage/configfile/
kind: Simple
apiVersion: k3d.io/v1alpha5
metadata:
  name: ${CLUSTER_NAME}
servers: 1
agents: 2
kubeAPI:
  host: ${HOSTNAME}
  hostIP: 0.0.0.0
  hostPort: "6443"
image: rancher/k3s:${K3S_VERSION}
subnet: "10.200.0.0/16"
volumes:
  - volume: ${SHARED_PATH}:/mnt/shared
    nodeFilters:
      - all
  - volume: ${SHARED_PATH}/default-local-pv:/opt/local-path-provisioner
    nodeFilters:
      - all
ports:
  # https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration#nodeport-service-port-range
  # - port: ${CURRENT_IP}:32600-32767:32600-32767 # a range of k3s nodeports exposed on host https://docs.k3s.io/cli/server#networking
  #   nodeFilters:
  #   - loadbalancer
  - port: 0.0.0.0:1080:30080
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:1443:30443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: 1m30s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048
  k3s:
    extraArgs:
      - arg: --disable=traefik,servicelb,local-storage,metrics-server
        nodeFilters:
          - server:*
      - arg: --tls-san=${CURRENT_IP}
        nodeFilters:
          - server:*
      - arg: --tls-san=${CURRENT_EXTERNAL_IP}
        nodeFilters:
          - server:*
      - arg: --tls-san=dxas90.duckdns.org
        nodeFilters:
          - server:*
      - arg: --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
        nodeFilters:
          - agent:*
      - arg: --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
        nodeFilters:
          - agent:*
    nodeLabels:
      - label: nerdctl/bypass4netns=true
        nodeFilters:
          - all
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    labels:
      - label: my.k3s.cluster=true
        nodeFilters:
          - all
      - label: nerdctl/bypass4netns=true
        nodeFilters:
          - all
env:
  - envVar: SHARED_PATH=${SHARED_PATH}
    nodeFilters:
      - all
