---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/external-secrets/external-secrets
  ref:
    tag: 0.9.1
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/deploy/charts/external-secrets
