apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base-full-common-resources


generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    note: generated
  labels:
    team: DevOps
    type: generated
labels:
- includeSelectors: true
  pairs:
    app: gitops-k8s
    owner: gitops
