kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
   - name: metrics
     protocol: TCP
     port: 15692
     targetPort: 15692
  selector:
    app: rabbitmq
