---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets
  path: ./k8s/cluster-common/apps/kube-system/external-secrets/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
