---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: security
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Authentik
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_REDIS__HOST: authentik-redis.security.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: "{{ .AUTHENTIK_DATABASE_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_DATABASE_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__HOST: postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname authentik
        AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: AUTHENTIK_DATABASE_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: postgres_username
    - secretKey: AUTHENTIK_DATABASE_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: postgres_password
    - secretKey: AUTHENTIK_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: secret_key
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: e09429a9-e6ef-49a1-bd0a-afc50145dc9c
        property: username
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: e09429a9-e6ef-49a1-bd0a-afc50145dc9c
        property: password
    - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: username
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: password
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: token
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7a5661cb-9655-422b-8506-b02900fbc4e1
        property: password
