---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./external-secret.yaml
  - ./gatus.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
