---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /databases/postgres/username
        version: v1
    - secretKey: password
      remoteRef:
        key: /databases/postgres/init_postgres_super_pass
        version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-app
  namespace: database
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: cloudnative-pg-app-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: /databases/postgres/username
        version: v1
    - secretKey: password
      remoteRef:
        key: /databases/postgres/password
        version: v1
