---
originRequest:
  http2Origin: true
  noTLSVerify: true

# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://traefik.networking.svc.cluster.local:443
    originRequest:
      originServerName: "ingress.${SECRET_DOMAIN}"
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://traefik.networking.svc.cluster.local:443
    originRequest:
      originServerName: "ingress.${SECRET_DOMAIN}"
  - hostname: "home.dxas90.xyz"
    service: http://home-service.networking.svc.cluster.local:8123
  # - service: http://traefik.networking.svc.cluster.local:80
  #   originRequest:
  #     connectTimeout: 10s
  - service: http_status:404

# https://developers.cloudflare.com/support/network/understanding-cloudflare-grpc-support/#requirements
