---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: exampleapp
  labels:
    app: gitops-k8s
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Mi
