---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "argocd-server-tls"
  namespace: networking
  labels:
    use-cloudflare-solver: "true"
spec:
  secretName: "argocd-server-tls"
  secretTemplate:
    labels:
      use-cloudflare-solver: "true"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "argocd.${SECRET_DOMAIN}"
  dnsNames:
    - "argocd.${SECRET_DOMAIN}"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingressroute
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.${SECRET_DOMAIN}`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.${SECRET_DOMAIN}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-server-tls
