---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: argocd-server-dns
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "argocd.${SECRET_DOMAIN}"
spec:
  endpoints:
    - dnsName: "argocd.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["ingress.${SECRET_DOMAIN}"]
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "argocd-server-tls"
  namespace: networking
  labels:
    use-cloudflare-solver: "true"
spec:
  secretName: "argocd-server-tls"
  secretTemplate:
    labels:
      use-cloudflare-solver: "true"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "argocd.${SECRET_DOMAIN}"
  dnsNames:
    - "argocd.${SECRET_DOMAIN}"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: argocd-server-ts
  namespace: networking
spec:
  weighted:
    services:
      - name: argocd-server
        namespace: argocd
        port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingressroute
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.${SECRET_DOMAIN}`)
      priority: 10
      services:
        - name: argocd-server-ts
          kind: TraefikService
          port: 80
    - kind: Rule
      match: Host(`argocd.${SECRET_DOMAIN}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-server-tls
