---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-argocd
  namespace: flux-system
spec:
  path: ./k8s/apps/argocd/argocd
  prune: true
  targetNamespace: argocd
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  dependsOn:
    - name: cluster-apps-traefik
      namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        namespace: flux-system
      - kind: Secret
        name: cluster-secrets
        namespace: flux-system
  patches:
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          labels:
            app.kubernetes.io/component: server
            app.kubernetes.io/name: argocd-server
            app.kubernetes.io/part-of: argocd
          name: argocd-server
          namespace: argocd
        spec:
          type: LoadBalancer
      target:
        kind: Service
        name: argocd-server
        namespace: argocd
        labelSelector: "app.kubernetes.io/name=argocd-server"
    - patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          labels:
            app.kubernetes.io/name: argocd-cmd-params-cm
            app.kubernetes.io/part-of: argocd
          name: argocd-cmd-params-cm
          namespace: argocd
        data:
          server.insecure: true
      target:
        kind: ConfigMap
        name: argocd-cmd-params-cm
        namespace: argocd
        labelSelector: "app.kubernetes.io/name=argocd-cmd-params-cm"
