---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-argocd
  namespace: argocd
spec:
  path: ./k8s/apps/argocd/argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  dependsOn:
    - name: cluster-apps-traefik
      namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        namespace: flux-system
      - kind: Secret
        name: cluster-secrets
        namespace: flux-system
