apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - github.com/argoproj/argo-cd/manifests/base?ref=stable
  - ./ingress.yaml
commonAnnotations:
  oncallPager: 800-555-1212
transformers:
  - labels.yaml
patchesStrategicMerge:
  - ./patch-argocd-cmd-params-cm.yaml
patchesJson6902:
    - patch: |-
        - op: replace
          path: /spec/type
          value: "LoadBalancer"
      target:
        kind: Service
        version: v1
        name: argocd-server
