apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - github.com/argoproj/argo-cd/manifests/base?ref=stable
  - ./ingress.yaml
# patches:
#   - patch: |-
#       apiVersion: v1
#       kind: Service
#       metadata:
#         name: argocd-server
#         namespace: argocd
#       spec:
#         type: LoadBalancer
#   - patch: |-
#       apiVersion: v1
#       kind: ConfigMap
#       metadata:
#         name: argocd-cmd-params-cm
#         namespace: argocd
#       data:
#         server.insecure: true
