apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - github.com/argoproj/argo-cd/manifests/base?ref=stable
  - ./ingress.yaml
  - ./patch-argocd-cmd-params-cm.yaml
# patches:
#   - path: ./patch-argocd-server.yaml
