apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - github.com/argoproj/argo-cd/manifests/base?ref=stable
  - ./ingress.yaml
# commonLabels:
#   system: argocd-k3d-cluster
commonAnnotations:
  oncallPager: 800-555-1212
# transformers:
  # - labels.yaml
patchesStrategicMerge:
#   - ./patch-argocd-server.yaml
  - ./patch-argocd-cmd-params-cm.yaml
patchesJson6902:
    - patch: |-
        - op: replace
          path: /spec/type
          value: "LoadBalancer"
      target:
        kind: Service
        version: v1
        name: argocd-server
    # - patch: |-
    #     - op: add
    #       path: /data/server.insecure
    #       value: "true"
    #     - op: add
    #       path: /data/server.repo.server.strict.tls
    #       value: "false"
    #     - op: add
    #       path: /data/server.repo.server.plaintext
    #       value: "true"
    #   target:
    #     kind: ConfigMap
    #     version: v1
    #     name: argocd-cmd-params-cm
