apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - github.com/argoproj/argo-cd/manifests/base?ref=stable
  - ./ingress.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd
        labels:
          app.kubernetes.io/component: server
          app.kubernetes.io/name: argocd-server
          app.kubernetes.io/part-of: argocd
      spec:
        type: LoadBalancer
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
        namespace: argocd
        labels:
          app.kubernetes.io/name: argocd-cmd-params-cm
          app.kubernetes.io/part-of: argocd
      data:
        server.insecure: true
