apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/argoproj/argo-cd/manifests/crds?ref=stable
  - github.com/argoproj/argo-cd/manifests/base?ref=stable
  - ./ingress.yaml
patches:
  - target:
      version: v1
      kind: Service
      name: argocd-server
      namespace: argocd
    patch: |-
      - op: replace
        path: /spec/type
        value: "LoadBalancer"
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
      namespace: argocd
    patch: |-
      - op: add
        path: /data/server/insecure
        value: "true"
