---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    kustomize.toolkit.fluxcd.io/name: cluster-apps-argocd
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
