---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-dns
  namespace: flux-system
spec:
  path: ./k8s/cluster-common/apps/networking/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
      namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
