apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:+VxDQ5r36Dk3vOtoULATGQb6IHdr3mFInrFJo7bgCwnfGAc+NO141A==,iv:5jb8hCciBYRk/SxC31iyvSd89cNUWnBYTyAViQeXujM=,tag:rrQcIsePjbC3tBPsqoKDtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NHdPUHFXMEVjemkwbjVU
            TFd1WGJ1ekFnTVdGM2c3a0gvaDdtMWdueTFFClVodnl4Wit0bjN5N1Q1U3ZTeHB0
            VFFzRkxEV1g0b1ZaeXlCWmJYY1BBVlEKLS0tIHRPRDV1YXdSU2JFUlNTMjZLc3FS
            Y01UcFZOclE5RUxyRytrRkhKOW56dG8KsnMnPKjUR/Tkl1V4IbEvDehzBifA6JSE
            yV0uQtoqS36BQlZ0ZY1BcyCfWix+VhehbGB0ugqvuyUiCKUOT1324g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-18T11:38:31Z"
    mac: ENC[AES256_GCM,data:0LNX515NOpU3UrSVV51Dh01Lff3Fmj78MCDFAcG663cX6kr4MuAKwf3Mmm4rhKjX4A+d2iicymmw7h6IB2Ei0PjqrWYCsFWTBlovpDk9JtGNctT1rc3K9QQI7i8GbRUz88g3OqbFnwAd0gn6QyFa5hzuimGPTiLdCm93mciNJyI=,iv:hYmeNRPR422D0zo0/8cnussj7eXG09iiD17KlISvoKs=,tag:64Y406lbQ5dxT5gy3RmDnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules|value|key)$
    version: 3.7.3
---
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pihole.md
apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: networking
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:sBZKt7H60xn04J/vuS6GSPaxZhXz1YpCVbA=,iv:F1vRTo9bnrq4A70GeMT0Zmt/auDd4uSQZymyxF/YYnQ=,tag:4uIsG+IcbCZjenvaJ23JjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NHdPUHFXMEVjemkwbjVU
            TFd1WGJ1ekFnTVdGM2c3a0gvaDdtMWdueTFFClVodnl4Wit0bjN5N1Q1U3ZTeHB0
            VFFzRkxEV1g0b1ZaeXlCWmJYY1BBVlEKLS0tIHRPRDV1YXdSU2JFUlNTMjZLc3FS
            Y01UcFZOclE5RUxyRytrRkhKOW56dG8KsnMnPKjUR/Tkl1V4IbEvDehzBifA6JSE
            yV0uQtoqS36BQlZ0ZY1BcyCfWix+VhehbGB0ugqvuyUiCKUOT1324g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-18T11:38:31Z"
    mac: ENC[AES256_GCM,data:0LNX515NOpU3UrSVV51Dh01Lff3Fmj78MCDFAcG663cX6kr4MuAKwf3Mmm4rhKjX4A+d2iicymmw7h6IB2Ei0PjqrWYCsFWTBlovpDk9JtGNctT1rc3K9QQI7i8GbRUz88g3OqbFnwAd0gn6QyFa5hzuimGPTiLdCm93mciNJyI=,iv:hYmeNRPR422D0zo0/8cnussj7eXG09iiD17KlISvoKs=,tag:64Y406lbQ5dxT5gy3RmDnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules|value|key)$
    version: 3.7.3
