apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZW7CrrJNAJYZ8O/UShW4Qg==,iv:SZikOKGmbc7F8Sgy9jpsQRUhma+FHP3P9p5kbnl0XBY=,tag:vrl8ScxMPpNK2IW4toPv5Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:m0J1rxXKDuCqlu4ELkY8PYl+tkFsYJVSZyU52HVCidtMF2Ta,iv:lKlbjw709w4Eml/9DiC9OZHLcpdicOe1DmojbuUcU1k=,tag:u06OAb3xEgFC9d/gd3D0NQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:92R3T1ihpSXcwEM=,iv:z61bG4nv0nB5yT1m4FRx2lHaur424A+I3g61Zkr9dUg=,tag:6Fv7GhxVJI3+askkEi0SkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUlh5SVBmaXo5TVpsK2Rr
            cHZMYk9Mam1Sb2ZNYzFBU0pvVlhNZmtyWnhvCmNuMzVBc1pUQWdmZm9INUE1WExa
            UGtiVThoYWlraDM3dUVpNzJZOW8xWTAKLS0tIHB4NVZ3WkU0MXZpTkEvckEvRVZs
            SWk5ZkhkMHRSTVFSN0Z1ck9WbHVaT0kK8qeA+pZ8G2kgmKQ3EbPN+dVwxu8/NpoV
            Rq2Pcsw1gO0tV4JwnfsfHrhwN3iEzb82pbwd8UcbWy0geBnTk1gayg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T08:10:19Z"
    mac: ENC[AES256_GCM,data:2A+5iei+UCt8Kbox+0E6wwVnDixBr60rK1TYNd+f3jscaDdD3pZ6TYPwFmInB2eViStAEHX68FeSSNi86CMnC/0c1Z0sM5UveKnX05quiHzDjFrF9JQT2K7APRQRX4B1AnIh/RLepg/hJiFFlvCgw1tkWm+Ml3NFDVCwSJOBV/Y=,iv:OY5IIOkOEMBXgVhKMSZ9nM893UpAqDPIFTMy8g4ZvrA=,tag:g7QIbiNdtlUsZNgOn08QCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
