---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PROWLARR__API_KEY: "{{ .PROWLARR__API_KEY }}"
        PROWLARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        PROWLARR__POSTGRES_PORT: "5432"
        PROWLARR__POSTGRES_USER: &dbUser "{{ .PROWLARR__POSTGRES_USER }}"
        PROWLARR__POSTGRES_PASSWORD: &dbPass "{{ .PROWLARR__POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
        PROWLARR__POSTGRES_LOG_DB: prowlarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PROWLARR__POSTGRES_USER
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: PROWLARR__POSTGRES_PASSWORD
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: PROWLARR__API_KEY
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
