---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.18.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: local-path-provisioner
  #     namespace: kube-system
  values: # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
    crds:
      create: true
