---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "6.12.0"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  maxHistory: 3
  values:
    replicaCount: 3
    podAnnotations:
      secret.reloader.stakater.com/reload: oauth2-proxy
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.4.0
    extraArgs:
      provider: github
      github-org: "github-org"
      github-team: "github-team"
      cookie-expire: 168h0m0s
      email-domain: "*"
      whitelist-domain: ".${SECRET_DOMAIN}"
      cookie-domain: ".${SECRET_DOMAIN}"
    config:
      existingSecret: oauth2-proxy
    service:
      main:
        ports:
          http:
            port: 4180
          metrics:
            port: 44180
            enabled: true
    probes:
      liveness: &probes
        enabled: false
    ingress:
      enabled: true
      ingressClassName: external-nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - auth.${SECRET_DOMAIN}
      path: /
      tls:
        - hosts:
            - auth.${SECRET_DOMAIN}
          secretName: auth.${SECRET_DOMAIN}-tls
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 105Mi
