---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-gitlab-k8s-runner
  namespace: flux-system
spec:
  path: ./k8s/cluster-home/apps/gitlab-home/gitlab-k8s-runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
