apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    listen: 4222
    http: 8222
    server_name: $POD_NAME

    jetstream: enabled

    jetstream {
      store_dir: /nats/storage
      max_mem: 500Mi
      max_file: 1Gi
    }

    cluster {
      name: nats-cluster
      port: 6222
      routes [
        nats://nats-0.nats:6222
        nats://nats-1.nats:6222
      ]

      cluster_advertise: $CLUSTER_ADVERTISE
      connect_retries: 30
    }
