apiVersion: v1
kind: Secret
metadata:
  name: gitlab-agent-home-agent-secrets
  namespace: gitlab-agent-home-agent
stringData:
  values.yaml: ENC[AES256_GCM,data:LFi8xrQWuk2rc5XkvNdg1uY+nKyLGQJkY5pV2uazEMjDVS6UUeZA5MWVlqQShI7JStuFdCgMsYicOzboLc17P6dSSBotGgGpTeD9EVXsJMsdHZuMLBAORYfw66Q7yHrp20a2yqujU6trJLqdCC/KL18=,iv:Jarr5ULRQ3bpnIFhoYgSs/FVrkQrZyZ9aLNVw/5zSVc=,tag:xVBO/TIgeHhYdfKYEEjA+A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTkxxZVIvaUV5QXNVaUVu
        RmV0eHlHU2NHTzNKSkdKV3ovcVMvUERJV2l3CkJiV1VhTUUvQ09wVm05Z25kSEx0
        b2hHM2VaUWZOYTB1aUhTL3Uyd1FkcGMKLS0tIG8wOUY4cnd5N0J1N29MYm81bmJB
        am1VTFN3SkdLSkVEQU9Vei81Z2Z2dzAKLtbjxZ/dhYXDwXHPQG2JX7LjaHtcNAO3
        t+dtVITZstArfdmMkuPAO/1wRA/gLHvPuFAM0DY6AlQ7DiLgGJc0Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-08-09T21:27:44Z"
  mac: ENC[AES256_GCM,data:4/5aNiNpC02siD8iYzTNL2gnccScyqhuQTircmPdBDd0lIK4kn4l7JUJ/7sz16j/XoV7DHm10pom6dqxw9ErUOT5rPaKzMDQyURt+tnAiRUtfoudIWCYhRPB0Yn7dyxV/GcLixIy4csMsQoHwV7rcwXG8aZS5vjAYTIs6itb0Oc=,iv:Z4ePabs7wmBEi6ohVkYIEABNVb0vLxu5fr8fF7XH7Do=,tag:HRYPCcjwAz/eXpAnQTA5XA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|externalName|tls|rules)$
  version: 3.7.3
