apiVersion: v1
kind: Secret
metadata:
  name: gitlab-agent-home-agent-secrets
  namespace: gitlab-agent-home-agent
stringData:
  values.yaml: ENC[AES256_GCM,data:+FDASdp6R/2yytT2L4eLylkBY0Cq8+Cj2eBezvwvqLKt0FflxU3fpOqccR6AAqemwEuHA4nciB81f0NpC79T8ROWmIe4XwW0NygmSzFOS/16bOFnae5wib4ZqjYVnfb8lwXHIuFQhXjQ1efBgWXJPpfYv6L5OeW7jau44K7djg==,iv:CojDNnIJ3wClv0RjSK6BuNeIy8jEXoNbvNDaPEAdBxE=,tag:mOP/GceqpCFrVJvtAxGtKg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SlJnMVNZNWN3Smd2bWUy
        R0UzWTdVQ1ZDUUVBM0IzMmZab2dhUnMxcnhFCnJ0eHlxdlBaZ2xXQkRyZzRobUI0
        eFlCa1BFUnRRMFJPc01JNUpDK2crak0KLS0tIEVPUElmUU5vSzZSb3pQVTlOalBh
        OEdJV1ZHUEgxV2I4S2l5NU5LV2V6SVEKguPYg2H4WQrUo9WWSkulGZ/L+tYgwJjb
        cUNrP1IfOQtBNyY0VMr27uOK2jifSUYyfR9Rg7DOsUEGON6ayWguTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-08-09T21:20:09Z"
  mac: ENC[AES256_GCM,data:x+TNIVl7P2eZqE6zZebRDuN1orB7bBJJ/Or3LUaH+hnNwoHCMNlI40NCHlrE4ROMfr8nnSD03U7DFEsNgy3smmVLhdqL6cdqd9r77J7Fmo4SmRsj9HARSiyJJ6IY29qoXMqIAVTglxK/V3w9Ytyn4y3/mgXpPs+EqJzGz0OzkyU=,iv:CqAscC9c7qmDLHm3NP6fnEsW19FpAoANiiYP1vZQmPo=,tag:YVQi13ySGNTGss5WcEHtRw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|externalName|tls|rules)$
  version: 3.7.3
