---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .username }}"
        INIT_POSTGRES_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_pass }}"
  data:
    - secretKey: username
      remoteRef:
        key: /databases/postgres/username
        version: v1
    - secretKey: password
      remoteRef:
        key: /databases/postgres/password
        version: v1
    - secretKey: postgres_super_pass
      remoteRef:
        key: /databases/postgres/init_postgres_super_pass
        version: v1
