---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-whoami-server
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-home/apps/networking/whoami-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-traefik
      namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
