---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 200Mi
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: etcd.png
          gethomepage.dev/name: Goldilocks
          gethomepage.dev/group: Monitoring
          external-dns.alpha.kubernetes.io/local-target: internal.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
        hosts:
          - host: &host goldilocks.${SECRET_DOMAIN}
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 200Mi
