---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vpa
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-common/apps/monitoring/vpa/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vpa
      namespace: monitoring
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
