---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: flagger
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    prometheus:
      install: true
    meshProvider: traefik
