---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secret
  namespace: downloads
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SONARR__API_KEY: "{{ .SONARR__API_KEY }}"
        SONARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .SONARR__POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .SONARR__POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_main
        SONARR__POSTGRES_LOG_DB: sonarr_log
        # # Postgres Init
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: SONARR__API_KEY
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: SONARR__POSTGRES_USER
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: SONARR__POSTGRES_PASSWORD
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
