---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.6.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: authentik-secrets
    podAnnotations:
      secret.reloader.stakater.com/reload: authentik-secrets
    ingress:
      enabled: true
      ingressClassName: external-nginx
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: authentik.png
        gethomepage.dev/name: Authentik
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/widget.type: authentik
        gethomepage.dev/widget.url: https://authentik.${SECRET_DOMAIN}
        gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: &host authentik.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    envFrom:
      - secretRef:
          name: authentik-secrets
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
    authentik:
      email:
        from: admin@${SECRET_DOMAIN}
        host: smtp.gmail.com
        port: 465
        use_ssl: true
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
