---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-secret
  namespace: downloads
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SABNZBD__API_KEY: "{{ .SABNZBD__API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD__NZB_KEY }}"
  data:
    - secretKey: SABNZBD__API_KEY
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: SABNZBD__NZB_KEY
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
