---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8s/cluster-common/apps/networking/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nginx-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8s/cluster-common/apps/networking/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  retryInterval: 1m
  timeout: 5m
