---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mylar
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-home/apps/downloads/mylar/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mylar
      namespace: downloads
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
