---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: downloads-gateway-vpnconfig
  namespace: vpn
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .private_key }}"
        WIREGUARD_PUBLIC_KEY: "{{ .public_key }}"
        WIREGUARD_PRESHARED_KEY: "{{ .preshared_key }}"
        WIREGUARD_ADDRESSES: " {{ .addresses }}"
        VPN_ENDPOINT_IP: "{{ .endpoint_ip }}"
  dataFrom:
  - extract:
      key: /global/services/wireguard/dev
      version: v1
