---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  values: # https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gateway/values.yaml
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776
    podAnnotations:
      reloader.stakater.com/auto: "true"
    DNS: 172.16.1.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.35.0@sha256:a98d1ec99e09a1b806aff7f0c3d8a133a8ede7d3d7a250b62029a39a61f01525
        env:
          - name: VPN_SERVICE_PROVIDER
            value: custom
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: "VPN_ENDPOINT_PORT"
            value: "51820"
          - name: "OPENVPN_PORT"
            value: "51820"
          - name: "PORT"
            value: "51820"
          - name: "DNS_ADDRESS"
            value: ${CURRENT_IP}
          - name: "TZ"
            value: ${TIMEZONE}
          - name: "DNS_KEEP_NAMESERVER"
            value: "on"
          - name: "LOG_LEVEL"
            value: "debug"
          - name: "HEALTH_TARGET_ADDRESS"
            value: "1.1.1.1:443"
          # - name: "HTTPPROXY"
          #   value: "on"
          # - name: "SHADOWSOCKS"
          #   value: "on"
        envFrom:
          - secretRef:
              name: downloads-gateway-vpnconfig
        networkPolicy:
          enabled: true
          egress:
            # Allow only VPN traffic to Internet
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic (default Wireguard)
                - port: 51820
                  protocol: UDP
            # Allow any traffic within k8s
            - to:
                - ipBlock:
                    # Cluster IPs (default k3s)
                    cidr: 10.0.0.0/8
        securityContext:
          capabilities:
            add:
              - NET_RAW
              - NET_ADMIN

      netshoot:
        enabled: true

    routed_namespaces:
      - development
      - downloads
      - monitoring
      - networking
      - tools

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 49
      VXLAN_IP_NETWORK: 172.16.1

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0
