---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cluster.yaml
  - ./gatus.yaml
  # - ./scheduledbackup.yaml
  - ./service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cloudnative-pg-cluster
      app.kubernetes.io/instance: cloudnative-pg-cluster
      app.kubernetes.io/part-of: cloudnative-pg
