---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-home
spec:
  interval: 30m
  targetNamespace: gitlab-home
  chart:
    spec:
      chart: gitlab-runner
      version: 0.55.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: # https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/main/values.yaml
    imagePullPolicy: IfNotPresent
  valuesFrom:
    - kind: Secret
      name: gitlab-k8s-runner-secrets
      valuesKey: values.yaml
      targetPath: config
