---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tools-harbor
  namespace: flux-system
spec:
  path: ./k8s/cluster-home/apps/tools/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-traefik
      namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 2m
  timeout: 10m
