---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-recyclarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-radarr
    - name: cluster-apps-sonarr
  path: ./k8s/cluster-home/apps/downloads/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: recyclarr
      namespace: downloads
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
