---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k3s-agent
  namespace: gitlab-home
spec:
  interval: 30m
  targetNamespace: gitlab-home
  chart:
    spec:
      chart: gitlab-agent
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: # https://gitlab.com/gitlab-org/charts/gitlab-agent/-/blob/main/values.yaml?ref_type=heads
    image:
      tag: v16.1.3
  valuesFrom:
    - kind: Secret
      name: gitlab-k8s-agent-secrets
      valuesKey: values.yaml
