apiVersion: v1
kind: Secret
metadata:
    name: gitlab-k8s-agent-secrets
    namespace: gitlab-home
stringData:
    values.yaml: ENC[AES256_GCM,data:vjsWZx3dnSGyeXudVOQ7yEEz/3c09b+o+TDg/3RNeYPOCrsC5t/swVWanmPSLgNaI+gB9GmXOnztT2St9+575Cfk//qlkNDuPljuHmiaPboGcU2QkQnWhN8R1EBRY+TTgVKE5k1irU3yC8jksaN8EWy5CcD18zZ5DgCFpDAl3fc=,iv:YZvglM8PdorRWA6RQmWLt7lua8BfDapdRE1HbFnpy9U=,tag:uP+dzLst8hnHRiQ2yL5hqA==,type:str]
    token: ENC[AES256_GCM,data:jz91vzVRk95uBtejQ9ixuKkeYscaNc3EBKKiTQscYR2wTHrSsdw2/vNvJ2OGSA8WE2c=,iv:hdP4RqQC/Fo8g7wlIDWhVhNlPAvWv3zAyJ8klfE58uc=,tag:cEJ6+lTgFxfZQlCmHKAHSg==,type:str]
    kasAddress: ENC[AES256_GCM,data:kZTYmPlJdQdPhJPPqIiZvVP4C8iOwKU5YulBBQmBhWNMvQlnTjvNtAoZ,iv:RGxDVyj7JgA43A/bD52FkG3fBKJxYclXQTBpEOnD2G8=,tag:PPF+eTqS1XKUFKAJOn2iPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZelJDOEoxeFpOaHdDK2tB
            RHpqVTR4d2VKVjdVRko5UU14TUpZQTlMZURRCm9LV1Nac3p4ZFhPQ0lBaVBLb3pl
            bVJxZ1V3R0RDNEhrMmZPajMzRmQrSFUKLS0tIEhEV21hQnNyczF2N240dGxndmcx
            Ukx5QzNramtJVm4wMldoaWF4aVRvaXMK2mqTmYW5FrYp3LIISKuXE41i109P6XT/
            kiO7R8Vk/WPpDNPz4Wbx1Qv+QI2PQ3CISiMJ4/s9PBt96rkU5v3gug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-15T11:21:05Z"
    mac: ENC[AES256_GCM,data:GEtZC1OgAGjefICXHdVVmgBUn1838gMf3ksWJPUWjWN7xmU9Vq7w+DN7/RBP0RSUw+ut3BlZOg9QV8eweVT1HgG/6IksCceUnKLDowRDWqJ7+kr4+h/IKDan7C4n6X7FhnNjkS5iCwP6oFz7Pni5Z0JUmcmlZMOODEJXdFQiCYk=,iv:b3gvbL0OGhNQK6g7SLnevWRSDg9Z2rGn7ke2ew7vzzg=,tag:4Ac2uV+TfZOiJEm9s1+P5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules)$
    version: 3.7.3
