---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - labels.yaml
resources:
  - ./cd-pipeline
  - ./ci-pipeline
  - ./infrastructure-control-planes
  - ./platform-orchestrator
  - ./registry