---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app syncthing
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      nameOverride: *app
    image:
      repository: syncthing/syncthing
      tag: 1.23.7
    env:
      PUID: 568
      PGID: 568
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 8384
      listen:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          listen:
            enabled: true
            port: 22000
            protocol: TCP
          listen-udp:
            enabled: true
            port: 22000
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host syncthing.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /mnt/shared/syncthing/
        mountPath: /var/syncthing
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 500M
