---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-secret
  namespace: downloads
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RADARR_API_KEY: |-
          {{ .radarr_token }}
        SONARR_API_KEY: |-
          {{ .sonarr_token }}
  data:
    - secretKey: radarr_token
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: sonarr_token
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
