---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mylar
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: longhorn
  #     namespace: storage
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/linuxserver/mylar3
      tag: version-v0.7.2@sha256:97800ddf62eba7c6eaf7cea1320331fea20b736a85cd604695b1fa8106c77511
    env:
      TZ: ${TIMEZONE}
      UID: 1000
      GID: 1000
    service:
      main:
        ports:
          http:
            port: 8090
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: mylar.png
          gethomepage.dev/name: Mylar
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: mylar
          gethomepage.dev/widget.url: http://mylar.downloads.svc.cluster.local:8090
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_MYLAR_TOKEN}}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/mylar/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn-config
    persistence:
      media:
        enabled: true
        existingClaim: downloads
        mountPath: /data
    resources:
      requests:
        cpu: 15m
        memory: 700M
      limits:
        memory: 1200M
