---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: v0.9.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
    installCRDs: true
    serviceMonitor:
      # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
      enabled: true
