---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-development-learn
  namespace: flux-system
spec:
  targetNamespace: development
  path: ./k8s/apps/development/learn
  prune: true
  sourceRef:
    kind: GitRepository
    name: learn
  wait: false
  interval: 40m
  retryInterval: 1m
  timeout: 5m
