---
# yaml-language-server: $schema=https://kubernetes-schemas.kashall.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 9.0.4
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  # All values at https://gitea.com/gitea/helm-chart
  values:
    image:
      repository: codeberg.org/forgejo/forgejo
      tag: 1.20.2-0
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      className: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      labels:
        use-cloudflare-solver: "true"
      hosts:
        - host: &host gitea.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      create: false
      mount: true
      claimName: gitea-pvc
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      labels:
        type: local
        app.kubernetes.io/name: gitea
      annotations:
        helm.sh/resource-policy: keep

    # databases
    postgresql:
      enabled: false
    mysql:
      enabled: false
    mariadb:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
      usePassword: false

    gitea:
      admin:
        username: gitea_admin
        password: ${GITEA_SECRET_PASSWORD}
        email: "admin@${SECRET_DOMAIN}"
      # See https://docs.gitea.io/en-us/config-cheat-sheet/
      config:
        APP_NAME: "Gitea for ${SECRET_DOMAIN}: Git with a cup of tea"
        #RUN_MODE: dev
        server:
          DISABLE_SSH: true
          ENABLE_GZIP: true
          PROTOCOL: http
          ROOT_URL: https://gitea.${SECRET_DOMAIN}
        database:
          DB_TYPE: sqlite3
          PATH: /data/gitea.db
        repository:
          ROOT: /data/repositories
        lfs:
          PATH: /data/lfs
        service:
          ALLOW_ONLY_EXTERNAL_REGISTRATION: false
          DEFAULT_ALLOW_CREATE_ORGANIZATION: true
          DEFAULT_ENABLE_TIMETRACKING: true
          DEFAULT_KEEP_EMAIL_PRIVATE: false
          DISABLE_REGISTRATION: true
          ENABLE_CAPTCHA: false
          ENABLE_NOTIFY_MAIL: false
          NO_REPLY_ADDRESS: noreply@${SECRET_DOMAIN}
          REGISTER_EMAIL_CONFIRM: false
          REQUIRE_SIGNIN_VIEW: true
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: false
        actions:
          ENABLED: true
          DEFAULT_ACTIONS_URL: https://github.com
        picture:
          DISABLE_GRAVATAR: false
          ENABLE_FEDERATED_AVATAR: true
        mailer:
          ENABLED: true
          FROM: "gitea@${SECRET_DOMAIN}"
          PROTOCOL: smtp
          SMTP_ADDR: smtp.sendgrid.net
          SMTP_PORT: 25
          USER: apikey
          PASSWD: ${SENDGRID_API_KEY}
        session:
          PROVIDER: file
          PROVIDER_CONFIG: /data/sessions
        cache:
          ENABLED: true
          ADAPTER: memory
        queue:
          TYPE: persistable-channel
        log:
          MODE: console, file
          LEVEL: Info
          ROOT_PATH: /data/log
        security:
          SECRET_KEY: ${GITEA_SECURITY_SECRET_KEY}

  valuesFrom:
  - kind: Secret
    name: "gitea-helm-values"
    valuesKey: gitea.yaml
    optional: false
