---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-oauth2-proxy
  namespace: flux-system
spec:
  dependsOn:
  path: ./k8s/cluster-common/apps/security/oauth2-proxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: oauth2-proxy
      namespace: security
  interval: 30m
  retryInterval: 1m
  timeout: 3m
