---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      tag: v3.3.2
    controller:
      replicas: 1 # active nas
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 8191