---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-tools
resources:
  - ./helmrelease.yaml
  - ./rbac.yaml
commonLabels:
  app.kubernetes.io/name: kyverno
  app.kubernetes.io/instance: kyverno
