---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-secret
  namespace: downloads
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        READARR__API_KEY: "{{ .READARR__API_KEY }}"
        READARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .READARR__POSTGRES_USER }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .READARR__POSTGRES_PASSWORD }}"
        READARR__POSTGRES_MAIN_DB: readarr_main
        READARR__POSTGRES_LOG_DB: readarr_log
        READARR__POSTGRES_CACHE_DB: readarr_cache
        # Postgres Init
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: READARR__API_KEY
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: READARR__POSTGRES_USER
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: READARR__POSTGRES_PASSWORD
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: READARR__API_KEY
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: /databases/postgres/palceholder
        version: v1
      sourceRef:
        storeRef:
          name: fake
          kind: ClusterSecretStore
