---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: downloads
  labels:
    app.kubernetes.io/name: downloads
spec:
  storageClassName: standard
  volumeName: downloads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  labels:
    type: local
    app.kubernetes.io/name: downloads
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/shared/downloads
