---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tdarr-node
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: cluster-apps-intel-device-plugins-gpu
  path: ./k8s/cluster-home/apps/downloads/tdarr/tdarr-node
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tdarr-node
      namespace: downloads
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
