---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: vpa
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 0.14.0
      resources:
        requests:
          cpu: 10m
          memory: 100M
        limits:
          memory: 200M
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
    updater:
      enabled: false
    admissionController:
      enabled: false
