---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-argocd-extras
  namespace: flux-system
spec:
  path: ./k8s/cluster-remote/apps/argocd/extras
  prune: true
  targetNamespace: argocd
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  dependsOn:
    - name: cluster-apps-argocd
      namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        namespace: flux-system
      - kind: Secret
        name: cluster-secrets
        namespace: flux-system
