# https://external-secrets.io/latest/provider/fake/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: fake
    namespace: kube-system
spec:
    provider:
        fake:
            data:
                - key: ENC[AES256_GCM,data:Fj1vQ2RKfM5Dsj558dQVSy89RFLKMqdahOne7w==,iv:bjRMNNF5pZgHFn0AbqkUG2cAgKdMXIt6VyWOEXLOvsQ=,tag:EFL52a9HV/UdzVjnb835tA==,type:str]
                  value: ENC[AES256_GCM,data:sy+iaobNHCQ+3aVJ2w==,iv:8clV9YyPVZiiapEixVC/qQhX3r8amCazEjvKRIUgqXY=,tag:f1OYAY3Os0fc+tm90uyGOg==,type:str]
                  version: ENC[AES256_GCM,data:ZPk=,iv:F3+d9yIYsi4IhWs+ReFvBx03lMkCrYJWDWCRCTBirK4=,tag:VdXBBbhffLwhow1EO/5OKA==,type:str]
                - key: ENC[AES256_GCM,data:2Wxmy+LjXuJjbRL/37zXP2zZJ3nXPvVY7hd5Qw==,iv:IyDi53qyoqhoyyQx1Y390ripPQWhFZEyS6m2kLt5KkE=,tag:An7jIjNT/kolL9RpUGzFVw==,type:str]
                  value: ENC[AES256_GCM,data:0I4vVGxCj/iQHd//fb3ugVXmUp8x6MZxkQ==,iv:3C4vyYUjt1PNOMBRw6H5jubfgDgykgjtj1dgDCG2SuA=,tag:3atQXv80TA77KWDDGfmlEA==,type:str]
                  version: ENC[AES256_GCM,data:eTQ=,iv:7INlvBhLml+PdrrfyY78B78UlR8U+9u5ROkktL9+8t8=,tag:yckEkwPdM+tZy6EbBRCyTQ==,type:str]
                - key: ENC[AES256_GCM,data:HkNAUmVWpcWM9eykz225zvc3AQ2ZKYyD0sfgV7U/eXSuJyM/p9tp2L2D/EY=,iv:dvtCEvPjS4hYGa3Usbdsun3EZ6fCxXf9CbZY2TKJYLg=,tag:2SDXZTtbedc9/vAPqLquJw==,type:str]
                  value: ENC[AES256_GCM,data:XoOT+7KPKhPVEMPzzrOtAkl2BGhAhPRRp/g=,iv:mYD7hZbUo1mGXKJGIsYvxjrphfymnol71XXZiWQrmBk=,tag:UjKTLdB64rBUk+IaiVi0PA==,type:str]
                  version: ENC[AES256_GCM,data:4EM=,iv:XcBqr29rErT7e6wtxtzWWrjK408X/bVEGCX/zLYojB8=,tag:xJC/i9ifEbB7pbYoW87GHw==,type:str]
                - key: ENC[AES256_GCM,data:aRl/8WKs+X4rap1zAkVbLmQQ86cQRh2p5r/hnsQ6lQ==,iv:4GMjTjw78I7m1nOicRPT7BEC8ST5hfIfZdt+yTRjRJk=,tag:6xe9lHtSluCfn55TDbPArA==,type:str]
                  value: ENC[AES256_GCM,data:dHfMDe+X3j6s081wrpcqJHAeeLcsygowJkhdI5P9r4VDITTH0FtXh/W7N3XKVOMSDza1,iv:oXwhbbrx0qOk1m+hE3PDY7tIiKcgzgJ9UqbGDQA71OM=,tag:3DxiPM4dSE69fG6G42J+BA==,type:str]
                  version: ENC[AES256_GCM,data:LXA=,iv:CdKo7fv8Z3TNy2RIMeNrG7AVCgD7tq6Yv0ASuzMqUo0=,tag:xoXddfHvGPniP6mqwLOBZw==,type:str]
                - key: ENC[AES256_GCM,data:s2k/ji3fgoWFhQ==,iv:662i8jcJaAMA1nhk4o56GOYRpU4zRlslqgngQmDcGGA=,tag:4+Lb+Y09bMHxuVUWWSKscQ==,type:str]
                  valueMap:
                    foo: ENC[AES256_GCM,data:xumnrucq5Q==,iv:WaCstO2Xn8kWMRBfbms8v4dsUhXuwQoJPH6pg86gCUk=,tag:sLPB7K/cgYJtUlH5HbwhLQ==,type:str]
                    other: ENC[AES256_GCM,data:4PQhkwk=,iv:hs9Swer2XeJW7eYVVEGa6RXjYMb0rjlbaOBMSrTQ4VY=,tag:0jLmPHaBbdAUdeuJFstiAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTWowMzQ3Nmx0NFR3UEh1
            dkY2eXJzR1RiNUtKbmkxZys0dDh1eVRLZGswCjF2MDZYRUltVDhoT2R4c2Z4VXp6
            Y3BpTDNVVkxpajZQUEEvSWk3Tmx3b1UKLS0tIFVjMjkrSVJZajE3UUg4RUxUaUNt
            dmFKVitJWGdwQmg2cnBqS2xPUXQ1dU0KGbCnZwNiDTjHgMhvzrHW6DhtUYCvXYvD
            ooJc2ntN84d4qbqiqDcnOTlneIKXhN5fVZDUl4xjrZ4taOtCO1QXyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-16T12:10:34Z"
    mac: ENC[AES256_GCM,data:mLnbu3Z4We5EjkEM+SYF5RoRRaFVmV6CLuBtE72Er7MyMjh+MBC5TryDDIMoG7FmL2uPnzTRcZjIjZ54qOJBanWcs3dMbPO+3NXch/YIHNq48vtlUjT7aGzE4A9b6Sb5SBv+Zm/ZG7dgIk1tjU8KJT0IklS5ParCv4bBhINnX1A=,iv:6fXV7EKNi+pd4Yac3lDwiWVUo2Ul7BQj0744iKct+Fs=,tag:2UiHn16aFlRDfOA4xAHs1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules|value|key)$
    version: 3.7.3
