---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
  labels:
    app: harbor
spec:
  storageClassName: standard
  volumeName: harbor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor
  labels:
    type: local
    app: harbor
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/shared/harbor
