apiVersion: v1
kind: Secret
metadata:
    name: harbor-helm-values
    namespace: tools
stringData:
    values.yaml: ENC[AES256_GCM,data:XtAKegij1LMp2KMPXhw8izeu+GFkeLOnI1sdAWYwz3Jp5NADo7z6TqJT+OdLflQsyJzk6CqZAxXxOcMGBaPBkbT7jkJfg0TcENbl/QOSGrZh6DjxoQB8/4wC173tzi1HSKuUdJzxzOVGichekaYKZ5xdfWHIPmKsYJAZM4ggfSZL+ksYyqlzY46ctRxrw3gB8XEN9e6WNvjv0RZMLng7Pqmyws8hi3/QHCPpLTdkgNrs3jqLcS483wijvLY/vMgzmT7Q53gQ3YTHU5Z/Na3Fv8WEweHgL0PTiWO7ucYT2lNb4LxZvruRVmNEIMfMpUSeDQdxvu3IcZFSttUlYogRuq9D89gGAJZrldHlI6gaBd5C9UJV6efPA2Bx1IHiZcBh02IPKk0Z9zhO,iv:kVyip3kXAHrhyAjWyc9HbVvWxaoaD+Eph2G0t+CMY5s=,tag:kdXd8KLMURBGyjFPeT1aLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaFh0ejZ5eFBQb0RTR3RN
            ZURGOUpRbkd2RkpVb0ZYdkZzRjZuS0V1cW5jCnF6b1JhaHlkdDFJV0lCdEphSEw5
            RktSeDkxZFJtUzhNWUNSL3lzZUF0T28KLS0tIENvTk1MNUJ5TUlzeCtxUmNSWFp1
            OVQvWXFrZUw4STEySzdOU1BMcFdzUVkKapZP9gxm50YWQRfAYm9C/+hbYKTKrF86
            R6L8QhI/QNW5TqI5sEEVU9aaG+C5U/C58dGE/f6Fen/KX9CoPGZavw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-11T13:01:52Z"
    mac: ENC[AES256_GCM,data:sCHD6enSC+4g4LOM+YN/Pvj4ByZ8gcv3pYixRakolOXqOTeF/wlmPrJ0I3VtpPWKr80OG2nNv/CnkjuqflMkcTWB1UpuVzT3aVQSTg6gIUsAvCF54uogg3IaD2mNZ3DM0h+3ch5a6z2FV2YeXocR9HpHPHVDvfueDFjsUpW5GI0=,iv:tXlyHTEMb8zEW5FWI1OHBbu53FvEJnIzmEA2cecZwtM=,tag:KTBeeKd20VR7GzUHwfas3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|externalName|tls|rules)$
    version: 3.7.3
