---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: readarr-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/readarr-develop
      tag: 0.3.1.2096@sha256:530d9f8d2033ffc1cc897edb1f0dc497a9845d6873eec2e8b3a3247c174bf24b
    env:
      TZ: ${TIMEZONE}
      READARR__INSTANCE_NAME: Readarr
      READARR__PORT: &port 80
      READARR__LOG_LEVEL: info
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: readarr.png
          gethomepage.dev/name: Readarr
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: readarr
          gethomepage.dev/widget.url: http://readarr.downloads.svc.cluster.local
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_READARR_TOKEN}}"
          nginx.ingress.kubernetes.io/configuration-snippet: |-
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/readarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn-config
    persistence:
      media:
        enabled: true
        existingClaim: downloads
        mountPath: /data
    resources:
      requests:
        cpu: 15m
        memory: 160M
      limits:
        memory: 330M
