---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: database
  labels:
    app.kubernetes.io/name: database
spec:
  storageClassName: standard
  volumeName: database
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    type: local
    app.kubernetes.io/name: database
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/shared/downloads
